//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.ObjectModel;
    using MVVMutils.Core;
    
    public partial class Movie : ObservableObject
    {
        private int _Id; public int Id { get { return _Id; } set { SetProperty(nameof(Id), ref _Id, value); } }
        private string _Name; public string Name { get { return _Name; } set { SetProperty(nameof(Name), ref _Name, value); } }
        private Nullable<int> _Duration; public Nullable<int> Duration { get { return _Duration; } set { SetProperty(nameof(Duration), ref _Duration, value); } }
        private Nullable<System.DateTime> _ReleaseDate; public Nullable<System.DateTime> ReleaseDate { get { return _ReleaseDate; } set { SetProperty(nameof(ReleaseDate), ref _ReleaseDate, value); } }
        private Nullable<byte> _Note; public Nullable<byte> Note { get { return _Note; } set { SetProperty(nameof(Note), ref _Note, value); } }
        private string _Data; public string Data { get { return _Data; } set { SetProperty(nameof(Data), ref _Data, value); } }
        private string _Poster; public string Poster { get { return _Poster; } set { SetProperty(nameof(Poster), ref _Poster, value); } }
        private bool _Viewed; public bool Viewed { get { return _Viewed; } set { SetProperty(nameof(Viewed), ref _Viewed, value); } }
        private int _Genre_Id; public int Genre_Id { get { return _Genre_Id; } set { SetProperty(nameof(Genre_Id), ref _Genre_Id, value); } }
        private System.DateTime _AddDate; public System.DateTime AddDate { get { return _AddDate; } set { SetProperty(nameof(AddDate), ref _AddDate, value); } }
    
        private Genre _Genre; public virtual Genre Genre { get { return _Genre; } set { SetProperty(nameof(Genre), ref _Genre, value); } }
    }
}
